#!/bin/bash

option1() {
echo "option1 test"
main
}
option2() {
echo "option2 test"
main
}
option3() {
echo "option3 test"
main
}
Quit() {
echo "User request exit"
exit
}


main() {
        echo "1) select option 1"
        echo "2) select option 2"
        echo "3) select option 3"
        echo "4) Quit"
        read -r -n 1 -s -p "choose: " choice
        case $choice in
        1)
                clear
                option1
;;
        2)
                clear
                option2
;; 
        3)
                clear
                option3
;;
        4)
                clear
                Quit
;;

        *)
                echo "invalid option $REPLY"
                clear 
                main
;;
        esac
}

main
exit
